version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cms-ncci-checker"
s3_bucket = ""
s3_prefix = "cms-ncci-checker"
region = "us-west-2"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
image_repositories = []
